// autogenerated by syzkaller (https://github.com/google/syzkaller)
// Modified to use a fork-based loop for reliable reproduction.

#define _GNU_SOURCE

#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/wait.h>
#include <time.h>

// A helper function to write a string to a file.
static bool write_file(const char* file, const char* what, ...)
{
	char buf[1024];
	va_list args;
	va_start(args, what);
	vsnprintf(buf, sizeof(buf), what, args);
	va_end(args);
	buf[sizeof(buf) - 1] = 0;
	int len = strlen(buf);
	int fd = open(file, O_WRONLY | O_CLOEXEC);
	if (fd == -1)
		return false;
	if (write(fd, buf, len) != len) {
		int err = errno;
		close(fd);
		errno = err;
		return false;
	}
	close(fd);
	return true;
}

// Injects a fault into the kernel on the Nth attempt.
static int inject_fault(int nth)
{
	int fd;
	fd = open("/proc/thread-self/fail-nth", O_RDWR);
	if (fd == -1) {
		// This should not fail if /proc is mounted
		perror("Failed to open /proc/thread-self/fail-nth");
		exit(1);
	}
	char buf[16];
	sprintf(buf, "%d", nth);
	if (write(fd, buf, strlen(buf)) != (ssize_t)strlen(buf)) {
		perror("Failed to write to /proc/thread-self/fail-nth");
		exit(1);
	}
	return fd;
}

// Sets up a few fault injection parameters for the kernel.
static void setup_fault()
{
	static struct {
		const char* file;
		const char* val;
		bool fatal;
	} files[] = {
		{"/sys/kernel/debug/failslab/ignore-gfp-wait", "N", true},
		{"/sys/kernel/debug/fail_futex/ignore-private", "N", false},
		{"/sys/kernel/debug/fail_page_alloc/ignore-gfp-highmem", "N", false},
		{"/sys/kernel/debug/fail_page_alloc/ignore-gfp-wait", "N", false},
		{"/sys/kernel/debug/fail_page_alloc/min-order", "0", false},
	};
	unsigned i;
	for (i = 0; i < sizeof(files) / sizeof(files[0]); i++) {
		if (!write_file(files[i].file, files[i].val)) {
			if (files[i].fatal)
				exit(1);
		}
	}
}

uint64_t r[1] = {0xffffffffffffffff};

// This function contains the actual syscalls from the syzkaller program.
void execute_program() {
	// Execute the mmap syscalls required by the reproducer.
	syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
			/*flags=*/0x32ul, /*fd=*/-1, /*offset=*/0ul);
	syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul, /*prot=*/7ul,
			/*flags=*/0x32ul, /*fd=*/-1, /*offset=*/0ul);
	syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
			/*flags=*/0x32ul, /*fd=*/-1, /*offset=*/0ul);

	// Setup kernel fault injection for this process.
	setup_fault();

	// The first syscall
	intptr_t res = syscall(__NR_socket, /*domain=*/0x23ul, /*type=*/5ul, /*proto=*/2);
	if (res != -1)
		r[0] = res;

	// Prepare data for the setsockopt syscall
	*(uint32_t*)0x20000040 = 1;

	// This is the critical part: inject a fault before setsockopt.
	// The bug is triggered when setsockopt fails with ENOMEM.
	inject_fault(51);
	syscall(__NR_setsockopt, /*fd=*/r[0], /*level=*/0x113, /*opt=*/1,
			/*val=*/0x20000040ul, /*len=*/4ul);

	// Clean up the socket.
	if (r[0] != 0xffffffffffffffff) {
		close(r[0]);
	}
}

int main(void)
{
	int i;
	// Loop a large number of times to reliably trigger the memory leak.
	for (i = 0; i < 100000; i++) {
		pid_t pid = fork();
		if (pid == -1) {
			perror("fork failed");
			exit(EXIT_FAILURE);
		} else if (pid == 0) {
			// Child process: executes the program once and exits.
			execute_program();
			_exit(EXIT_SUCCESS);
		} else {
			// Parent process: waits for the child to finish.
			int status;
			if (waitpid(pid, &status, 0) == -1) {
				perror("waitpid failed");
				exit(EXIT_FAILURE);
			}
		}
	}

	return 0;
}
