// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define __STDC_EMBED_NOT_FOUND__ 0
#define __STDC_EMBED_FOUND__ 1
#define __STDC_EMBED_EMPTY__ 2

#define _GNU_SOURCE

#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/wait.h>

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

static int inject_fault(int nth)
{
  int fd;
  fd = open("/proc/thread-self/fail-nth", O_RDWR);
  if (fd == -1)
    exit(1);
  char buf[16];
  sprintf(buf, "%d", nth);
  if (write(fd, buf, strlen(buf)) != (ssize_t)strlen(buf))
    exit(1);
  return fd;
}

static void setup_fault()
{
  static struct {
    const char* file;
    const char* val;
    bool fatal;
  } files[] = {
      {"/sys/kernel/debug/failslab/ignore-gfp-wait", "N", true},
      {"/sys/kernel/debug/fail_futex/ignore-private", "N", false},
      {"/sys/kernel/debug/fail_page_alloc/ignore-gfp-highmem", "N", false},
      {"/sys/kernel/debug/fail_page_alloc/ignore-gfp-wait", "N", false},
      {"/sys/kernel/debug/fail_page_alloc/min-order", "0", false},
  };
  unsigned i;
  for (i = 0; i < sizeof(files) / sizeof(files[0]); i++) {
    if (!write_file(files[i].file, files[i].val)) {
      if (files[i].fatal)
        exit(1);
    }
  }
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
  int i;
  for (i = 0; i < 100000; i++) {
    int pid = fork();
    if (pid < 0) {
      perror("fork failed");
      exit(1);
    }
    if (pid == 0) {
      // This is the child process
      syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
                 /*flags=*/0x32ul, /*fd=*/-1, /*offset=*/0ul);
      syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul, /*prot=*/7ul,
                 /*flags=*/0x32ul, /*fd=*/-1, /*offset=*/0ul);
      syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
                 /*flags=*/0x32ul, /*fd=*/-1, /*offset=*/0ul);
      setup_fault();
      intptr_t res = 0;
      res = syscall(__NR_socket, /*domain=*/0x23ul, /*type=*/5ul, /*proto=*/2);
      if (res != -1)
        r[0] = res;
      *(uint32_t*)0x20000040 = 1;
      inject_fault(51);
      syscall(__NR_setsockopt, /*fd=*/r[0], /*level=*/0x113, /*opt=*/1,
                 /*val=*/0x20000040ul, /*len=*/4ul);
      exit(0); // Child process exits after one run
    }/* else {
      // This is the parent process
      wait(NULL); // Wait for the child to finish
    } */
  }
  return 0;
}
